package com.adapreload.instrumentation.model

import com.adapreload.instrumentation.trace.Json
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertSame
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File
import java.util.Locale
import kotlin.math.abs

/**
 * Phase D: the Kotlin Layer 2 adapter against the notebook's PyTorch formulation
 * (layer2_golden.json, generated by tools/make_layer2_golden.py).
 *
 * Tolerances come from FP32 rounding, not from the observed Kotlin error. The fixture records how
 * far the PyTorch FP32 reference itself is from an FP64 run of the same steps
 * (fp32_vs_fp64_rounding); each tolerance is about 6-10x that envelope.
 */
class Layer2AdapterTest {

    companion object {
        /** Losses and logits (|value| < 16, FP32 ulp <= 9.5e-7): envelope <= 4.4e-7. */
        const val LOGIT_TOLERANCE = 5e-6

        /** W and b after one step (|value| < 3.9e-3, FP32 ulp 2.3e-10): envelope 2.7e-10. */
        const val STATE_ONE_STEP_TOLERANCE = 2e-9

        /** W and b after the 30-step sequence (|value| < 7.8e-3, FP32 ulp 4.7e-10): envelope 1.7e-9. */
        const val STATE_SEQUENCE_TOLERANCE = 1e-8
    }

    private class Step(m: Map<*, *>) {
        val hidden = floats(m["hidden"])
        val backboneLogits = floats(m["backbone_logits"])
        val target = (m["target"] as Long).toInt()
        val finalLogitsBefore = doubles(m["final_logits_before_update"])
        val lossBefore = (m["loss_before"] as Number).toDouble()
    }

    private val golden: Map<*, *> by lazy { Json.parse(File("src/androidTest/assets/layer2_golden.json").readText()) as Map<*, *> }
    private val oneStep: Map<*, *> get() = golden["one_step"] as Map<*, *>
    private val sequence: Map<*, *> get() = golden["sequence"] as Map<*, *>
    private val steps: List<Step> by lazy { (sequence["steps"] as List<*>).map { Step(it as Map<*, *>) } }
    private val launches: IntArray by lazy { ints(sequence["launches"]) }

    private val model: Layer1Model by lazy {
        Layer1Model.load(
            File("src/main/assets/${Layer1Assets.MANIFEST}").readText(),
            File("src/main/assets/${Layer1Assets.WEIGHTS}").readBytes(),
        )
    }

    /** Context for sequence step i (predicting launch i): the last <= 20 launches, left-padded. */
    private fun sequenceContext(i: Int): IntArray {
        val real = launches.copyOfRange(maxOf(0, i - 20), i)
        return IntArray(20 - real.size) + real
    }

    @Test
    fun fixtureComesFromTheFrozenCheckpointAndUsesTheFrozenSettings() {
        assertEquals("adapreload-layer2-golden", golden["format"])
        assertEquals(Layer1Model.CHECKPOINT_SHA256, (golden["source"] as Map<*, *>)["checkpoint_sha256"])
        assertEquals(0.001, golden["learning_rate"])
        assertEquals(30, steps.size)
        assertEquals(30L, sequence["update_count"])
        for ((i, s) in steps.withIndex()) {
            assertEquals(launches[i + 1], s.target)
            assertTrue("real app id", s.target in 1..87)
            assertNotEquals("no repeated launch (T3)", launches[i], s.target)
        }

        // The fixture inputs are what the Android Layer 1 computes for the same contexts (Phase C bound).
        val inputs = listOf(Triple(ints(oneStep["context"]), floats(oneStep["hidden"]), floats(oneStep["backbone_logits"]))) +
            steps.indices.map { Triple(sequenceContext(it + 1), steps[it].hidden, steps[it].backboneLogits) }
        var hiddenErr = 0.0
        var logitErr = 0.0
        for ((context, hidden, logits) in inputs) {
            val p = model.predict(context)
            hiddenErr = maxOf(hiddenErr, maxAbs(hidden, p.hidden))
            logitErr = maxOf(logitErr, maxAbs(logits, p.logits))
        }
        println(fmt("Layer 1 vs fixture inputs (31 contexts): hidden %.3e, logits %.3e", hiddenErr, logitErr))
        assertTrue(hiddenErr <= Layer1Parity.FP32_LOGIT_TOLERANCE)
        assertTrue(logitErr <= Layer1Parity.FP32_LOGIT_TOLERANCE)
    }

    /** D1: with W = 0 and b = 0 the adapter changes nothing. */
    @Test
    fun d1ZeroStateLeavesLayer1Unchanged() {
        val adapter = Layer2Adapter()
        assertEquals(0L, adapter.updateCount)
        assertTrue(adapter.weightSnapshot().all { it.toRawBits() == 0 } && adapter.weightSnapshot().size == 88 * 64)
        assertTrue(adapter.biasSnapshot().all { it.toRawBits() == 0 } && adapter.biasSnapshot().size == 88)

        val goldenContexts = Layer1Parity.parseGolden(File("src/androidTest/assets/layer1_golden.json").readText())
            .cases.map { ints(it["context"]) }
        val contexts = goldenContexts + listOf(ints(oneStep["context"])) + (1..30).map(::sequenceContext)
        var probabilityErr = 0.0
        for (context in contexts) {
            val l1 = model.predict(context)
            val learner = Layer2OnlineLearner(Layer2Adapter())
            val l2 = learner.predict(l1.hiddenFp32(), l1.logitsFp32())
            assertEquals(0L, l2.updatesBefore)
            assertTrue(adapter.adapterLogits(l1.hiddenFp32()).all { it == 0f })
            assertArrayEquals(l1.logitsFp32(), l2.finalLogits, 0f)
            assertArrayEquals("ranking of all 87 apps", l1.rankedAppIds(), l2.rankedAppIds())
            assertEquals(87, l2.probabilities.size)
            probabilityErr = maxOf(probabilityErr, maxAbs(l2.probabilities, l1.probabilities))
        }
        println(fmt("D1: %.0f contexts, Layer 2 (zero) vs Layer 1 probabilities %.3e", contexts.size.toDouble(), probabilityErr))
        assertTrue(probabilityErr <= Layer1Parity.FP32_PROBABILITY_TOLERANCE)
    }

    /** D2: one SGD step equals the PyTorch step. */
    @Test
    fun d2OneStepMatchesPyTorch() {
        val hidden = floats(oneStep["hidden"])
        val logits = floats(oneStep["backbone_logits"])
        val target = (oneStep["target"] as Long).toInt()
        val adapter = Layer2Adapter()

        val loss = adapter.update(hidden, logits, target)
        val after = adapter.finalLogits(hidden, logits)
        val lossErr = abs(loss - (oneStep["loss_before"] as Number).toDouble())
        val wErr = maxAbs(adapter.weightSnapshot(), doubles(oneStep["weight_after"]))
        val bErr = maxAbs(adapter.biasSnapshot(), doubles(oneStep["bias_after"]))
        val afterErr = maxAbs(after, doubles(oneStep["final_logits_after_same_hidden"]))
        println(fmt("D2: target %.0f, loss %.6f; |dloss| %.3e, W %.3e, b %.3e, final logits after %.3e",
            target.toDouble(), loss, lossErr, wErr, bErr, afterErr))

        assertEquals(1L, adapter.updateCount)
        assertTrue(lossErr <= LOGIT_TOLERANCE)
        assertTrue(wErr <= STATE_ONE_STEP_TOLERANCE)
        assertTrue(bErr <= STATE_ONE_STEP_TOLERANCE)
        assertTrue(afterErr <= LOGIT_TOLERANCE)
        // The padding output is in the loss (unmasked, as offline), so its bias moves by -lr * p0.
        val b = adapter.biasSnapshot()
        assertTrue(b[0] < 0f && b[target] > 0f)
        assertTrue(after[target] > logits[target])
    }

    /** D3: prediction t uses the state after t - 1 updates, and target t cannot change prediction t. */
    @Test
    fun d3PredictionPrecedesItsSingleUpdate() {
        val learner = Layer2OnlineLearner()
        val predictions = ArrayList<Layer2Prediction>()
        var logitErr = 0.0
        var lossErr = 0.0
        for ((t, s) in steps.withIndex()) {
            assertFalse(learner.hasPendingPrediction)
            val prediction = learner.predict(s.hidden, s.backboneLogits)
            assertEquals(t.toLong(), prediction.updatesBefore)
            assertEquals(t.toLong(), learner.adapter.updateCount)
            assertTrue(learner.hasPendingPrediction)
            assertTrue(runCatching { learner.predict(s.hidden, s.backboneLogits) }.isFailure)   // no second prediction
            val update = learner.reveal(s.target)
            assertSame(prediction, update.prediction)
            assertEquals(t + 1L, update.updateCount)
            assertTrue(runCatching { learner.reveal(s.target) }.isFailure)                      // no second update
            predictions += prediction
            lossErr = maxOf(lossErr, abs(update.lossBefore - s.lossBefore))
        }
        // Recorded predictions are not changed by the updates that follow them.
        for ((t, s) in steps.withIndex()) logitErr = maxOf(logitErr, maxAbs(predictions[t].finalLogits, s.finalLogitsBefore))
        println(fmt("D3: 30 prequential steps; final logits before update %.3e, loss %.3e", logitErr, lossErr))
        assertTrue(logitErr <= LOGIT_TOLERANCE)
        assertTrue(lossErr <= LOGIT_TOLERANCE)

        // Same history, different target at t: prediction t is identical, prediction t + 1 is not.
        for (t in listOf(0, 1, 14, 28)) {
            val a = Layer2OnlineLearner()
            val b = Layer2OnlineLearner()
            for (i in 0 until t) for (l in listOf(a, b)) {
                l.predict(steps[i].hidden, steps[i].backboneLogits)
                l.reveal(steps[i].target)
            }
            val pa = a.predict(steps[t].hidden, steps[t].backboneLogits)
            val pb = b.predict(steps[t].hidden, steps[t].backboneLogits)
            assertArrayEquals(pa.finalLogits, pb.finalLogits, 0f)
            assertArrayEquals(predictions[t].finalLogits, pa.finalLogits, 0f)
            a.reveal(steps[t].target)
            b.reveal(steps[t].target % 87 + 1)
            val next = steps[t + 1]
            assertFalse(a.predict(next.hidden, next.backboneLogits).finalLogits
                .contentEquals(b.predict(next.hidden, next.backboneLogits).finalLogits))
        }

        // reveal before any prediction is refused.
        assertTrue(runCatching { Layer2OnlineLearner().reveal(steps[0].target) }.isFailure)
    }

    /** D4: the 30-step sequence ends in the PyTorch state. */
    @Test
    fun d4RepeatedUpdatesMatchPyTorch() {
        val adapter = Layer2Adapter()
        var lossErr = 0.0
        for (s in steps) lossErr = maxOf(lossErr, abs(adapter.update(s.hidden, s.backboneLogits, s.target) - s.lossBefore))
        val wErr = maxAbs(adapter.weightSnapshot(), doubles(sequence["weight_after"]))
        val bErr = maxAbs(adapter.biasSnapshot(), doubles(sequence["bias_after"]))
        println(fmt("D4: 30 updates; W %.3e, b %.3e, loss %.3e", wErr, bErr, lossErr))
        assertEquals(30L, adapter.updateCount)
        assertTrue(wErr <= STATE_SEQUENCE_TOLERANCE)
        assertTrue(bErr <= STATE_SEQUENCE_TOLERANCE)
        assertTrue(lossErr <= LOGIT_TOLERANCE)

        // The learner applies exactly these updates and no others.
        val learner = Layer2OnlineLearner()
        for (s in steps) {
            learner.predict(s.hidden, s.backboneLogits)
            learner.reveal(s.target)
        }
        assertArrayEquals(adapter.weightSnapshot(), learner.adapter.weightSnapshot(), 0f)
        assertArrayEquals(adapter.biasSnapshot(), learner.adapter.biasSnapshot(), 0f)
    }

    /** D5: reset returns to W = 0, b = 0, no updates, no pending prediction. */
    @Test
    fun d5ResetRestoresTheInitialState() {
        val learner = Layer2OnlineLearner()
        for (s in steps) {
            learner.predict(s.hidden, s.backboneLogits)
            learner.reveal(s.target)
        }
        learner.predict(steps[0].hidden, steps[0].backboneLogits)
        learner.reset()
        assertFalse(learner.hasPendingPrediction)
        assertEquals(0L, learner.adapter.updateCount)
        assertTrue(learner.adapter.weightSnapshot().all { it.toRawBits() == 0 })
        assertTrue(learner.adapter.biasSnapshot().all { it.toRawBits() == 0 })
        assertTrue(runCatching { learner.reveal(steps[0].target) }.isFailure)

        // After reset the adapter behaves exactly like a new one.
        val fresh = Layer2Adapter()
        val hidden = floats(oneStep["hidden"])
        val logits = floats(oneStep["backbone_logits"])
        val target = (oneStep["target"] as Long).toInt()
        assertEquals(fresh.update(hidden, logits, target), learner.adapter.update(hidden, logits, target), 0.0)
        assertArrayEquals(fresh.weightSnapshot(), learner.adapter.weightSnapshot(), 0f)
        assertArrayEquals(fresh.biasSnapshot(), learner.adapter.biasSnapshot(), 0f)
    }

    /** Padding id 0 is never an observed target, and never ranked. */
    @Test
    fun paddingIsNeverATargetOrARankedApp() {
        val hidden = floats(oneStep["hidden"])
        val logits = floats(oneStep["backbone_logits"])
        val learner = Layer2OnlineLearner()
        learner.predict(hidden, logits)
        for (bad in listOf(0, -1, 88)) {
            assertTrue(runCatching { learner.reveal(bad) }.exceptionOrNull() is IllegalArgumentException)
            assertTrue(runCatching { learner.adapter.update(hidden, logits, bad) }.exceptionOrNull() is IllegalArgumentException)
        }
        // A refused target changes nothing; the prediction still waits for its real target.
        assertEquals(0L, learner.adapter.updateCount)
        assertTrue(learner.adapter.weightSnapshot().all { it == 0f } && learner.adapter.biasSnapshot().all { it == 0f })
        assertTrue(learner.hasPendingPrediction)
        learner.reveal((oneStep["target"] as Long).toInt())
        assertEquals(1L, learner.adapter.updateCount)

        // Ranking ignores the padding logit however large it is.
        val withPadding = logits.copyOf().also { it[0] = 100f }
        val a = Layer2Prediction(logits, 0)
        val b = Layer2Prediction(withPadding, 0)
        assertArrayEquals(a.probabilities, b.probabilities, 0.0)
        assertArrayEquals(a.rankedAppIds(), b.rankedAppIds())
        assertTrue(b.rankedAppIds().sorted() == (1..87).toList())
        assertEquals(1.0, b.probabilities.sum(), 1e-12)

        assertTrue(runCatching { Layer2Adapter().adapterLogits(FloatArray(63)) }.isFailure)
        assertTrue(runCatching { Layer2Adapter().finalLogits(hidden, FloatArray(87)) }.isFailure)
    }
}

private fun doubles(v: Any?): DoubleArray = (v as List<*>).map { (it as Number).toDouble() }.toDoubleArray()

private fun ints(v: Any?): IntArray = (v as List<*>).map { (it as Long).toInt() }.toIntArray()

/** FP32 values from the fixture; each must be exactly representable (it was written from a float32 tensor). */
private fun floats(v: Any?): FloatArray = doubles(v).map { d ->
    d.toFloat().also { require(it.toDouble() == d) { "$d is not an FP32 value" } }
}.toFloatArray()

private fun maxAbs(a: FloatArray, b: DoubleArray): Double {
    require(a.size == b.size)
    return a.indices.maxOf { abs(a[it] - b[it]) }
}

private fun maxAbs(a: DoubleArray, b: DoubleArray): Double {
    require(a.size == b.size)
    return a.indices.maxOf { abs(a[it] - b[it]) }
}

private fun fmt(format: String, vararg args: Double) = String.format(Locale.ROOT, format, *args.toTypedArray())
